INSERT INTO APP.POSITION (ID, NAME) VALUES (1, 'Developer');
INSERT INTO APP.POSITION (ID, NAME) VALUES (2, 'QA');
INSERT INTO APP.POSITION (ID, NAME) VALUES (3, 'SysAdmin');
INSERT INTO APP.POSITION (ID, NAME) VALUES (4, 'UX');
INSERT INTO APP.POSITION (ID, NAME) VALUES (5, 'DBA');